import Product from "./models/Product"
import { fetchProductData } from "./services/apiService"
import { NetworkError, DataError } from "./util/errorHandler"
import { calculateDiscount } from "./util/discountCalculator"
import { calculateTax } from "./util/taxCalculator"